#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#include "crc32.h"

#define PREFIX   "ISO_"
#define DEF_FILE "defs.dat"

#define HEADER_FILE "src/constants.h"
#define HEADER_NAME "CONSTANTS"

#define BUF_SIZE 256

void strip(char *);

int
main(int argc, char *argv[])
{
	char     buf[BUF_SIZE+1];
	FILE     *file;
	FILE     *header;
	size_t   len;
	uint32_t crc;

	file = fopen(DEF_FILE, "r");
	if(!file) {
		perror(DEF_FILE);
		exit(EXIT_FAILURE);
	}

	header = fopen(HEADER_FILE, "w");
	if(!header) {
		perror(HEADER_FILE);
		exit(EXIT_FAILURE);
	}

	fputs("/*\n * NOTE: PLEASE do no edit; autogenerated.\n"
	      " * check +generate_header.c+ for more info.\n"
	      " */\n\n", header);

	fprintf(header, "#ifndef _%s_H_\n#define _%s_H_\n\n",
	                                     HEADER_NAME, HEADER_NAME);

	while(!feof(file)) {
		fgets(&buf[0], BUF_SIZE, file);

		strip(buf);

		/* ignore lines starting with # */
		if(buf[0]=='#')
			continue;

		len = strlen(buf);
		if(!len)
			continue;

		crc = crc32(buf, len);

		fprintf(header, "#define %s%s %u\n", PREFIX, buf, crc);
	}

	fprintf(header, "\n#endif\n");

	fclose(file);
	fclose(header);

	return EXIT_SUCCESS;
}

void
strip(char *s)
{
	char   *ptr  = s;
	size_t len   = strlen(s);
	size_t size  = 0;

	if(!len)
		return;

	while(isblank(*ptr) || isspace(*ptr)) {
		size++;
		ptr++;
	}

	if(size)
		memcpy(s, ptr, size);

	ptr = s + len - 1;

	while((isblank(*ptr) || isspace(*ptr)) && ptr != s) --ptr;

	*(++ptr) = '\0';
	return;
}

